apiVersion: v1
kind: Secret

metadata:
  name: digital-secret
  namespace: expense-system

type: Opaque

stringData:
  DB_USER: expense_user
  DB_PASSWORD: password
  SECRET_KEY: digital-twin-super-secret-key