apiVersion: v1
kind: Secret

metadata:
  name: mysql-secret
  namespace: expense-system

type: Opaque

stringData:
  MYSQL_ROOT_PASSWORD: root
  MYSQL_DATABASE: expense_db
  MYSQL_USER: expense_user
  MYSQL_PASSWORD: password
  