apiVersion: v1
kind: Secret

metadata:
  name: expense-secret
  namespace: expense-system

type: Opaque

stringData:
  DB_USER: expense_user
  DB_PASSWORD: password
  SECRET_KEY: expense-super-secret-key
